{
 "title": "TH1",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "TH1 temp/target",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  temp\nFROM therm\nWHERE\n  $__timeFilter(datetime) AND id = 'TH1'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  target\nFROM therm\nwhere $__timeFilter(datetime) and id = 'TH1'"
    }
   ]
  },
  {
   "title": "TH1 comp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  temp,\n  id,\n  target\nFROM therm\nWHERE\n  $__timeFilter(datetime) and id = 'TH1'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Increase target",
   "type": "cloudspout-button-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  temp\nFROM therm\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Decrease target",
   "type": "cloudspout-button-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  temp\nFROM therm\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  datetime AS \"time\",\r\n  temp,\r\n  state,\r\n  id,\r\n  target\r\nFROM therm\r\nwhere id = 'TH1'\r\nORDER BY datetime desc"
    }
   ]
  }
 ]
}