apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    access: proxy
    url: 192.168.16.1:5432
    database: test
    user: postgres
    secureJsonData:
      password: password
    jsonData:
      sslmode: 'disable'
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1200
      timescaledb: true