datasources:
  - name: Postgres
    type: postgres
    url: 172.18.0.1:5432
    database: test
    user: postgres
    secureJsonData:
      password: 'password'
    jsonData:
      sslmode: 'disable'
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1401
      timescaledb: true