version: "3.3"
services:
  timescale:
    image: timescale/timescaledb:latest-pg14
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
    networks:
      - gateway

  grafana:
    build:
      context: ./grafana
      dockerfile: dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    user: '104'
    environment:
      - GF_INSTALL_PLUGINS=https://github.com/cloudspout/cloudspout-button-panel/releases/download/7.0.23/cloudspout-button-panel.zip;cloudspout-button-panel
    networks:
      - gateway
    
  rest-opcua:
    container_name: rest-opcua
    build:
      context: ./rest-opcua
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      ENV: PRODUCTION
      TZ: "Europe/Madrid"
    restart: always
    networks:
      - gateway

networks:
  gateway:
    driver: bridge
    
