services:
  timescale:
    image: timescale/timescaledb:latest-pg14
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test

  grafana:
    build:
      context: ./grafana
      dockerfile: dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    user: '104'
    
