services:
  timescale:
    image: timescale/timescaledb:latest-pg14
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password

  grafana:
    build:
      context: ./Grafana
      dockerfile: dockerfile
    ports:
      - 3000:3000
    user: '104'
    volumes:
      - ./Grafana/provisioning:/etc/grafana/provisioning
